# Generated by Django 4.2.2 on 2023-06-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
