# Generated by Django 4.2.2 on 2023-06-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
